### ISSUE TITLE
sha1 is inappropriate for this use case

### ISSUE THREAD

**Issue by zeebo** [dhalden/sha1_extension#1]
You'll fall pray to extension attacks. https://en.m.wikipedia.org/wiki/Length_extension_attack

For example say I'm a site operator for foo.com and you generate a password with this. So your private portion is some good strong secret, and I guess the site specific portion to be "foo". Then I can take your output and generate what your password would be for any site specific portion with prefix "foo" with guessing limited to the length of your secret. 

You want to do an HMAC construction to avoid the above. They're pretty easy to write. Just some bit twiddling and more calls to sha1. Or just be aware and make all your site specific phrases share the same suffix. Or not care because it's super unlikely anyone will try that at all. :)

**Comment by dhalden** [comment]
This was an interesting one to deal with in javascript. Mainly because I'm not too familiar with it. I added what should be bit-padding + 2 calls to sha1, as well as the bitwise ORs and XORs recommended in the wikiepdia HMAC article.

It was as close to HMAC as I could make it, but some of the things were problematic because I don't know javascript that well.
